--- #YAML:1.0
name:               App-CmdDirs
version:            1.00
abstract:           Perform a command in subdirectories
author:
    - Drew Stephens <drew@dinomite.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    App::FatPacker:  0.9.6
requires:
    ExtUtils::MakeMaker:  6.31
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
